name = 'swap-meet-custom-dink-webhook'
main = "src/index.js"
compatibility_date = "2024-11-22"
[observability.logs]
enabled = true

[triggers]
crons = ["0 16 * * 1"] # Monday 16:00 UTC

[[kv_namespaces]]
binding = "CA_PROGRESS"
id = "cc17ea160ebc4aa390969602aad00259"
preview_id = "508dbfa39b384308b07e3644d57ccad5"

[[d1_databases]]
binding = "PETS_DB"
database_name = "dink_pets"
database_id = "63602ced-0117-4f2b-a525-53d035bc10e2"
migrations_dir = "migrations/pets"

[[d1_databases]]
binding = "CRAB_DB"
database_name = "dink_crab_kc"
database_id = "ae46ffbe-fdd8-45dc-a712-efa039c25c0c"
migrations_dir = "migrations/crab_kc"

[[d1_databases]]
binding = "LOOT_DB"
database_name = "dink_loot"
database_id = "1308d5b3-3507-4901-b128-8c58ed747756"
migrations_dir = "migrations/loot"

[[d1_databases]]
binding = "WEEKLY_RECAP_DB"
database_name = "dink_weekly_recap"
database_id = "c938df6a-ff7a-4954-9ed9-4cfb0782bcb2"
migrations_dir = "migrations/weekly_recap"
